CREATE TABLE `tco_option` (
	`SITE_ID` VARCHAR(10) NOT NULL COMMENT 'SITE ID',
	`COMP_ID` VARCHAR(10) NOT NULL COMMENT '회사ID',
	`CATEGORY` VARCHAR(30) NOT NULL COMMENT '옵션Category',
	`OPTION_ID` VARCHAR(30) NOT NULL COMMENT '옵션ID',
	`OPTION_CODE` VARCHAR(100) NULL DEFAULT NULL COMMENT '옵션 CODE',
	`OPTION_VALUE` VARCHAR(200) NULL DEFAULT NULL COMMENT '옵션값',
	`OPTION_BUILDER` VARCHAR(2000) NULL DEFAULT NULL COMMENT '생성스크립트',
	`USE_YN` CHAR(1) NULL DEFAULT NULL COMMENT '사용여부',
	`DESCRIPTION` VARCHAR(2000) NULL DEFAULT NULL COMMENT '설명',
	`REG_USER_ID` VARCHAR(30) NOT NULL COMMENT '등록자아이디',
	`REG_DTM` DATETIME NOT NULL COMMENT '등록일',
	`UPD_USER_ID` VARCHAR(30) NOT NULL COMMENT '수정자아이디',
	`UPD_DTM` DATETIME NOT NULL COMMENT '수정일',
	PRIMARY KEY (`OPTION_ID`),
	UNIQUE INDEX `TCO_OPTION_PK` (`OPTION_ID`)
)
COMMENT='공통옵션'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;

CREATE TABLE `tco_code` (
	`SITE_ID` VARCHAR(10) NOT NULL COMMENT 'SITE ID',
	`COMP_ID` VARCHAR(10) NOT NULL COMMENT '회사ID',
	`CODE_GROUP` VARCHAR(30) NOT NULL COMMENT '코드 그룹',
	`CODE_ID` VARCHAR(30) NOT NULL COMMENT '코드ID',
	`CODE` VARCHAR(30) NULL DEFAULT NULL COMMENT 'CODE',
	`CODE_VALUE` VARCHAR(200) NULL DEFAULT NULL COMMENT 'CODE 값',
	`USE_YN` CHAR(1) NULL DEFAULT NULL COMMENT '사용여부',
	`CODE_ORD` INT(2) NULL DEFAULT NULL COMMENT '코드순서',
	`CODE_TYPE` CHAR(1) NULL DEFAULT NULL COMMENT '코드형태(\'G\'그룹,\'C\'코드)',
	`ETC_INFO` VARCHAR(500) NULL DEFAULT NULL COMMENT '기타 정보',
	`DESCRIPTION` VARCHAR(2000) NULL DEFAULT NULL COMMENT '설명',
	`REG_USER_ID` VARCHAR(30) NOT NULL COMMENT '등록자아이디',
	`REG_DTM` DATETIME NOT NULL COMMENT '등록일',
	`UPD_USER_ID` VARCHAR(30) NOT NULL COMMENT '수정자아이디',
	`UPD_DTM` DATETIME NOT NULL COMMENT '수정일',
	PRIMARY KEY (`CODE_ID`),
	UNIQUE INDEX `TCO_CODE_PK` (`CODE_ID`)
)
COMMENT='공통코드'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;


CREATE TABLE `tco_comp` (
	`SITE_ID` VARCHAR(10) NOT NULL COMMENT 'SITE ID',
	`COMP_ID` VARCHAR(30) NOT NULL COMMENT '회사ID',
	`COMP_CODE` VARCHAR(30) NOT NULL COMMENT '회사코드',
	`COMP_NAME` VARCHAR(30) NOT NULL COMMENT '회사명',
	`USE_YN` CHAR(1) NULL DEFAULT NULL COMMENT '사용여부',
	`COMP_ORD` INT(2) NULL DEFAULT NULL COMMENT '순번',
	`ETC_INFO` VARCHAR(500) NULL DEFAULT NULL COMMENT '기타 정보',
	`DESCRIPTION` VARCHAR(2000) NULL DEFAULT NULL COMMENT '설명',
	`REG_USER_ID` VARCHAR(30) NOT NULL COMMENT '등록자아이디',
	`REG_DTM` DATETIME NOT NULL COMMENT '등록일',
	`UPD_USER_ID` VARCHAR(30) NOT NULL COMMENT '수정자아이디',
	`UPD_DTM` DATETIME NOT NULL COMMENT '수정일',
	PRIMARY KEY (`COMP_ID`),
	UNIQUE INDEX `TCO_COMP_PK` (`COMP_ID`),
	UNIQUE INDEX `TCO_COMP_CODE_IDX` (`COMP_CODE`)
)
COMMENT='회사정보'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
ROW_FORMAT=DEFAULT
;

CREATE TABLE `tco_dept` (
	`COMP_ID` VARCHAR(30) NOT NULL COMMENT '회사ID',
	`DEPT_ID` VARCHAR(30) NOT NULL COMMENT '조직ID',
	`DEPT_CODE` VARCHAR(30) NOT NULL COMMENT '조직CODE',
	`DEPT_NAME` VARCHAR(100) NOT NULL COMMENT '조직명',
	`P_DEPT_ID` VARCHAR(30) NULL DEFAULT NULL COMMENT '상위조직ID',
	`USE_YN` CHAR(1) NULL DEFAULT NULL COMMENT '사용여부',
	`DEPT_LVL` INT(2) NULL DEFAULT NULL COMMENT '조직레벨',
	`DEPT_ORD` INT(2) NULL DEFAULT NULL COMMENT '조직순서',
	`ETC_INFO` VARCHAR(500) NULL DEFAULT NULL COMMENT '기타 정보',
	`DESCRIPTION` VARCHAR(2000) NULL DEFAULT NULL COMMENT '설명',
	`REG_USER_ID` VARCHAR(30) NOT NULL COMMENT '등록자아이디',
	`REG_DTM` DATETIME NOT NULL COMMENT '등록일',
	`UPD_USER_ID` VARCHAR(30) NOT NULL COMMENT '수정자아이디',
	`UPD_DTM` DATETIME NOT NULL COMMENT '수정일',
	PRIMARY KEY (`DEPT_ID`),
	UNIQUE INDEX `TCO_DEPT_PK` (`DEPT_ID`)
)
COMMENT='부서정보'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
ROW_FORMAT=DEFAULT
;

CREATE TABLE `tco_user` (
	`USER_ID` VARCHAR(30) NOT NULL COMMENT '사용자ID',
	`SITE_ID` VARCHAR(10) NOT NULL COMMENT 'SITE ID',
	`USER_NAME` VARCHAR(100) NOT NULL COMMENT '사용자명',
	`USER_NICK_NAME` VARCHAR(100) NOT NULL COMMENT '사용자별명',
	`LOGIN_ID` VARCHAR(30) NULL DEFAULT NULL COMMENT '로그인ID',
	`LOGIN_PWD` VARCHAR(256) NOT NULL COMMENT '로그인비밀번호',
	`USER_STATUS` CHAR(1) NULL DEFAULT NULL COMMENT '사용자상태( 101 : 재직, 999 : 퇴직, )',
	`GRADE_CODE`  VARCHAR(10) NULL DEFAULT NULL COMMENT '직위코드',
	`ETC_INFO` VARCHAR(500) NULL DEFAULT NULL COMMENT '기타 정보',
	`DESCRIPTION` VARCHAR(2000) NULL DEFAULT NULL COMMENT '설명',
	`REG_USER_ID` VARCHAR(30) NOT NULL COMMENT '등록자아이디',
	`REG_DTM` DATETIME NOT NULL COMMENT '등록일',
	`UPD_USER_ID` VARCHAR(30) NOT NULL COMMENT '수정자아이디',
	`UPD_DTM` DATETIME NOT NULL COMMENT '수정일',
	PRIMARY KEY (`USER_ID`),
	UNIQUE INDEX `TCO_DEPT_PK` (`USER_ID`)
)
COMMENT='사용자정보'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
ROW_FORMAT=DEFAULT
;

CREATE TABLE `tco_dept_user` (
	`USER_ID` VARCHAR(30) NOT NULL COMMENT '사용자ID',
	`DEPT_ID` VARCHAR(30) NOT NULL COMMENT '부서ID',
	`GRADE_CODE` VARCHAR(10) NULL DEFAULT NULL COMMENT '직위코드',
	`POSITION_CODE` VARCHAR(10) NULL DEFAULT NULL COMMENT '직책코드',
	`DEPT_TYPE_CODE` CHAR(1) NULL DEFAULT NULL COMMENT '부서형태(O :원부서, A : 겸직부서 , D : 파견부서 )',
	`DEPT_ORDER` INT NULL COMMENT '부서순서',
	`ETC_INFO` VARCHAR(500) NULL DEFAULT NULL COMMENT '기타 정보',
	`REG_USER_ID` VARCHAR(30) NOT NULL COMMENT '등록자아이디',
	`REG_DTM` DATETIME NOT NULL COMMENT '등록일',
	`UPD_USER_ID` VARCHAR(30) NOT NULL COMMENT '수정자아이디',
	`UPD_DTM` DATETIME NOT NULL COMMENT '수정일',
	PRIMARY KEY (`DEPT_ID`, `USER_ID`),
	UNIQUE INDEX `TCO_ORG_PK` (`DEPT_ID`, `USER_ID`)
)
COMMENT='부서별 사용자 정보'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
ROW_FORMAT=DEFAULT
;

CREATE TABLE `tco_user_contact` (
	`USER_ID`   VARCHAR(30) NOT NULL COMMENT '사용자ID',
	`CONTACT_TYPE_CODE` VARCHAR(10) NOT NULL COMMENT '연락처형태코드 ( PHONE : 전화번호, CELLPH : 핸드폰 번호, MAIL : 이메일, ADDR:주소)',
	`CONTACT_ORD` INT(2) NOT NULL COMMENT '연락처 순번',
	`CONTACT_VAL` VARCHAR(500) NOT NULL COMMENT '연락처 값',
	`ETC_INFO` VARCHAR(500) NULL DEFAULT NULL COMMENT '기타 정보',
	`CONTACT_CMT` VARCHAR(100) NULL DEFAULT NULL COMMENT '연락처 커멘트',
	`REG_USER_ID` VARCHAR(30) NOT NULL COMMENT '등록자아이디',
	`REG_DTM` DATETIME NOT NULL COMMENT '등록일',
	`UPD_USER_ID` VARCHAR(30) NOT NULL COMMENT '수정자아이디',
	`UPD_DTM` DATETIME NOT NULL COMMENT '수정일',
	PRIMARY KEY (`USER_ID`),
	UNIQUE INDEX `TCO_DEPT_PK` (`USER_ID`, `CONTACT_TYPE_CODE`, `CONTACT_ORD`)
)
COMMENT='사용자 연락처 정보'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;

CREATE TABLE `tco_menu` (
	`MENU_ID` VARCHAR(30) NOT NULL COMMENT '메뉴아이디',
	`MENU_NAME` VARCHAR(100) NOT NULL COMMENT '메뉴명',
	`MENU_ICON` VARCHAR(50) NOT NULL COMMENT '메뉴아이콘',
	`PARENT_MENU_ID` VARCHAR(30) NOT NULL COMMENT '상위메뉴아이디',
	`MENU_URL` VARCHAR(100) NULL DEFAULT NULL COMMENT '메뉴URL',
	`MENU_METHOD` VARCHAR(10) NULL DEFAULT NULL COMMENT '메뉴METHOD',
	`MENU_ORDER` INT(11) NULL DEFAULT NULL COMMENT '메뉴순번',
	`REG_USER_ID` VARCHAR(30) NOT NULL COMMENT '등록자아이디',
	`REG_DTM` DATETIME NOT NULL COMMENT '등록일',
	`UPD_USER_ID` VARCHAR(30) NOT NULL COMMENT '수정자아이디',
	`UPD_DTM` DATETIME NOT NULL COMMENT '수정일'
)
COMMENT='메뉴 관리 테이블'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
ROW_FORMAT=DEFAULT
;


CREATE TABLE `tco_auth_group` (
	`AUTH_GROUP_ID` VARCHAR(30) NOT NULL COMMENT '권한그룹아이디',
	`AUTH_GROUP_NAME` VARCHAR(100) NOT NULL COMMENT '권한그룹명',
	`COMP_ID` VARCHAR(30) NOT NULL COMMENT '회사아이디',
	`AUTH_GROUP_TYPE` VARCHAR(10) NOT NULL COMMENT '권한그룹형태(AUTHGROUP,FOLDER)',
	`PARENT_AUTH_GROUP_ID` VARCHAR(30) NULL DEFAULT NULL COMMENT '상위권한그룹아이디',
	`DESCRIPTION` VARCHAR(2000) NULL DEFAULT NULL COMMENT '설명',
	`REG_USER_ID` VARCHAR(30) NOT NULL COMMENT '등록자아이디',
	`REG_DTM` DATETIME NOT NULL COMMENT '등록일',
	`UPD_USER_ID` VARCHAR(30) NOT NULL COMMENT '수정자아이디',
	`UPD_DTM` DATETIME NOT NULL COMMENT '수정일'
)
COMMENT='권한 그룹 정보'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
ROW_FORMAT=DEFAULT


CREATE TABLE `tco_auth_grant` (
	`AUTH_GRANT_ID` VARCHAR(30) NULL DEFAULT NULL COMMENT '권한 부여 아이디',
	`AUTH_ASSIGN_ID` VARCHAR(30) NULL DEFAULT NULL COMMENT '권한 매핑 멤버',
	`AUTH_GRANT_TYPE` CHAR(1) NULL DEFAULT NULL COMMENT '권한형태(권한그룹,사용자, 부서)',
	`DESCRIPTION` VARCHAR(2000) NULL DEFAULT NULL COMMENT '설명',
	`REG_USER_ID` VARCHAR(30) NOT NULL COMMENT '등록자아이디',
	`REG_DTM` DATETIME NOT NULL COMMENT '등록일',
	`UPD_USER_ID` VARCHAR(30) NOT NULL COMMENT '수정자아이디',
	`UPD_DTM` DATETIME NOT NULL COMMENT '수정일'
)
COMMENT='권한 부여 정보'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
ROW_FORMAT=DEFAULT
;

